import React from "react";
import { useEffect } from "react";
import { useDispatch } from "react-redux";
import "./Finalpage.scss";
import { emtyCart } from "./redux/cart";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const Finalpage = () => {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(emtyCart());
    localStorage.removeItem("name");
    localStorage.removeItem("first_name_Login");
    localStorage.removeItem("email_or_mobile");
    localStorage.removeItem("password");
    localStorage.removeItem("SignUPname");
    toast.success(
      "All data generated by this WebApp cleared from local storage!",
      {
        position: "top-center",
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
      }
    );
  }, []);
  return (
    <>
      <div className="final_page__wrapper">
        <div className="container-fluid">
          <div className="row">
            <div className="col">
              <div className="final_page_container text-center">
                <h2>😄 Thanx for visiting my Amazon app</h2>
                <img src="./imgs/happycat.jpg" width={300} alt="" />
                <h3>
                  👉 It's a Front-end of Amazon, created using React, Redux and
                  Axios library 👈
                </h3>
                <h4>
                  This webapp don't store any garbage in your machine! After
                  visiting this page all unnecessary cookies or local storage
                  data generated by this webapp deleted from your browser
                </h4>
                <h1>
                  You can visit my Website
                  <a
                    target="_newtab"
                    className="mx-3"
                    href="https://thehemant.com"
                  >
                    TheHemant.com
                  </a>
                  or my github repository
                  <a
                    target="_newtab"
                    className="mx-3"
                    href="https://github.com/webdev-hemant"
                  >
                    WebDev-Hemant
                  </a>
                  for full documentation
                </h1>
                {/* <img src="./imgs/blob/blob-2.svg" alt="" /> */}
                {/* <img src="./imgs/blob/wave.png" alt="" /> */}
              </div>
            </div>
          </div>
        </div>
      </div>
      <ToastContainer newestOnTop style={{ zIndex: "9999999999999999" }} />
    </>
  );
};

export default Finalpage;
